package com.wealthmanagementsystem.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Asset entity representing master data of available investment assets.
 * 
 * Mapped to database table: assets
 * 
 * Relationships:
 * - M:N with Portfolio via PortfolioAsset join table
 * 
 * Business Rules:
 * - Master data seeded at application setup
 * - Static pricing for MVP (no real-time market data)
 * - Assets can be referenced by multiple portfolios
 * 
 * @author Wealth Management System
 * @version 1.0
 * @since Phase 4.2
 */
@Entity
@Table(name = "assets")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Asset {
    
    /**
     * Unique identifier for asset.
     * Primary key, auto-generated by database.
     * Type: BIGINT AUTO_INCREMENT
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Full name of the asset.
     * Type: VARCHAR(255), NOT NULL
     * Example: "Vanguard S&P 500 ETF"
     */
    @Column(name = "asset_name", nullable = false, length = 255)
    private String assetName;
    
    /**
     * Type of asset.
     * Enum values: STOCK, BOND, CASH, MUTUAL_FUND, ETF
     * Type: ENUM stored as VARCHAR(20), NOT NULL
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "asset_type", nullable = false, length = 20)
    private AssetType assetType;
    
    /**
     * Detailed description of the asset.
     * Type: TEXT, NULLABLE
     * Example: "Tracks the performance of the S&P 500 index"
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    /**
     * Timestamp when asset was created.
     * Auto-managed by JPA @PrePersist lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when asset was last updated.
     * Auto-managed by JPA @PreUpdate lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
