package com.wealthmanagementsystem.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * FinancialGoal entity representing user's financial objectives.
 * 
 * Mapped to database table: financial_goals
 * 
 * Relationships:
 * - N:1 with User (many goals per user)
 * - NO relationship with Portfolio (independent financial planning)
 * 
 * Business Rules:
 * - User can have multiple financial goals
 * - Progress is calculated at runtime, not stored (always fresh)
 * - Status determined by comparing projected vs target dates
 * 
 * Calculated Fields (NOT persisted):
 * - current_progress_percentage = (current_savings / target_amount) * 100
 * - months_to_target = (target_amount - current_savings) / monthly_contribution
 * - projected_completion_date = NOW() + months_to_target
 * - status = ON_TRACK / AT_RISK / OFF_TRACK
 * 
 * @author Wealth Management System
 * @version 1.0
 * @since Phase 4.2
 */
@Entity
@Table(name = "financial_goals")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class FinancialGoal {
    
    /**
     * Unique identifier for goal.
     * Primary key, auto-generated by database.
     * Type: BIGINT AUTO_INCREMENT
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Reference to owning user.
     * Many-to-one relationship (many goals per user).
     * Foreign key: user_id -> users.id
     * Type: BIGINT, NOT NULL
     * Cascade: User deleted = Goal deleted
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    
    /**
     * User-defined name for the goal.
     * Type: VARCHAR(255), NOT NULL
     * Example: "House Down Payment", "Retirement Fund"
     */
    @Column(name = "goal_name", nullable = false, length = 255)
    private String goalName;
    
    /**
     * Target amount to achieve in IDR.
     * Type: DECIMAL(15,2), NOT NULL
     * Range: 0.00 to 999,999,999,999,999.99 (up to 999 trillion IDR)
     * Example: 500000000.00 (Rp 500 juta)
     */
    @Column(name = "target_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal targetAmount;
    
    /**
     * Target date to achieve the goal.
     * Type: DATE, NOT NULL
     * Example: 2030-12-31
     */
    @Column(name = "target_date", nullable = false)
    private LocalDate targetDate;
    
    /**
     * Goal category for classification.
     * Enum values: RETIREMENT, EDUCATION, PROPERTY, EMERGENCY, OTHER
     * Type: ENUM stored as VARCHAR(15), NOT NULL
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 15)
    private GoalCategory category;
    
    /**
     * Current amount already saved towards this goal.
     * Type: DECIMAL(15,2), NOT NULL, DEFAULT 0
     * Example: 50000000.00 (Rp 50 juta saved)
     */
    @Column(name = "current_savings", nullable = false, precision = 15, scale = 2)
    private BigDecimal currentSavings = BigDecimal.ZERO;
    
    /**
     * Monthly savings contribution towards this goal.
     * Type: DECIMAL(15,2), NOT NULL, DEFAULT 0
     * Example: 5000000.00 (Rp 5 juta per month)
     */
    @Column(name = "monthly_contribution", nullable = false, precision = 15, scale = 2)
    private BigDecimal monthlyContribution = BigDecimal.ZERO;
    
    /**
     * Timestamp when goal was created.
     * Auto-managed by JPA @PrePersist lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when goal was last updated.
     * Auto-managed by JPA @PreUpdate lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
