package com.wealthmanagementsystem.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Portfolio entity representing user's investment portfolios.
 * 
 * Mapped to database table: portfolios
 * 
 * Relationships:
 * - N:1 with User (many portfolios belong to one user)
 * - M:N with Asset via PortfolioAsset join table
 * 
 * Business Rules:
 * - User can have multiple portfolios (1:N relationship)
 * - Each portfolio has different risk levels and allocations
 * - Portfolio composition defined via PortfolioAsset join table
 * 
 * @author Wealth Management System
 * @version 1.0
 * @since Phase 4.2
 */
@Entity
@Table(name = "portfolios")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Portfolio {
    
    /**
     * Unique identifier for portfolio.
     * Primary key, auto-generated by database.
     * Type: BIGINT AUTO_INCREMENT
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Reference to owning user.
     * Many-to-one relationship (many portfolios per user).
     * Foreign key: user_id -> users.id
     * Type: BIGINT, NOT NULL
     * Cascade: User deleted = Portfolio deleted (managed by DB FK)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    
    /**
     * User-defined name for portfolio.
     * Type: VARCHAR(100), NOT NULL
     * Example: "Conservative Retirement", "Aggressive Growth"
     */
    @Column(name = "portfolio_name", nullable = false, length = 100)
    private String portfolioName;
    
    /**
     * Portfolio classification/strategy type.
     * Type: VARCHAR(50), NOT NULL
     * Example: "Balanced", "Income-Focused", "Growth"
     */
    @Column(name = "portfolio_type", nullable = false, length = 50)
    private String portfolioType;
    
    /**
     * Risk level of this portfolio.
     * Enum values: LOW, MEDIUM, HIGH
     * Type: ENUM stored as VARCHAR(10), NOT NULL
     * 
     * Portfolio risk level may differ from user's risk profile
     * (user can experiment with different strategies)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", nullable = false, length = 10)
    private RiskLevel riskLevel;
    
    /**
     * Timestamp when portfolio was created.
     * Auto-managed by JPA @PrePersist lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when portfolio was last updated.
     * Auto-managed by JPA @PreUpdate lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
