package com.wealthmanagementsystem.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * PortfolioAsset entity representing M:N relationship between Portfolio and Asset.
 * 
 * Mapped to database table: portfolio_assets
 * 
 * This is a join table with business data (allocation_percentage).
 * 
 * Relationships:
 * - N:1 with Portfolio (many allocations per portfolio)
 * - N:1 with Asset (many portfolios can use same asset)
 * 
 * Business Rules:
 * - One asset can appear only once per portfolio (UNIQUE constraint)
 * - allocation_percentage must be between 0 and 100
 * - Sum of all allocations per portfolio should equal 100% (validated in service layer)
 * 
 * @author Wealth Management System
 * @version 1.0
 * @since Phase 4.2
 */
@Entity
@Table(
    name = "portfolio_assets",
    uniqueConstraints = @UniqueConstraint(columnNames = {"portfolio_id", "asset_id"})
)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PortfolioAsset {
    
    /**
     * Unique identifier for portfolio-asset allocation.
     * Primary key, auto-generated by database.
     * Type: BIGINT AUTO_INCREMENT
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Reference to portfolio that contains this asset.
     * Many-to-one relationship (many allocations per portfolio).
     * Foreign key: portfolio_id -> portfolios.id
     * Type: BIGINT, NOT NULL
     * Cascade: Portfolio deleted = PortfolioAsset deleted
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "portfolio_id", nullable = false)
    private Portfolio portfolio;
    
    /**
     * Reference to the asset being allocated.
     * Many-to-one relationship (asset used in many portfolios).
     * Foreign key: asset_id -> assets.id
     * Type: BIGINT, NOT NULL
     * Cascade: RESTRICT (cannot delete asset if allocated in portfolios)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "asset_id", nullable = false)
    private Asset asset;
    
    /**
     * Allocation percentage for this asset in the portfolio.
     * Type: DECIMAL(5,2), NOT NULL
     * Range: 0.00 to 999.99 (typically 0.00-100.00)
     * 
     * Example: 50.00 means 50% allocation to this asset
     * 
     * Validation: Sum of all allocations per portfolio should equal 100%
     * (validated in GoalService layer, not DB level for MVP flexibility)
     */
    @Column(name = "allocation_percentage", nullable = false, precision = 5, scale = 2)
    private BigDecimal allocationPercentage;
    
    /**
     * Timestamp when allocation was created.
     * Auto-managed by JPA @PrePersist lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when allocation was last updated.
     * Auto-managed by JPA @PreUpdate lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
