package com.wealthmanagementsystem.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * RiskProfile entity representing user's risk assessment results.
 * 
 * Mapped to database table: risk_profiles
 * 
 * Relationships:
 * - N:1 with User (belongs to user, 1:1 enforced by UNIQUE constraint)
 * 
 * Business Rules:
 * - One user can have exactly one risk profile (UNIQUE constraint on user_id)
 * - Risk level determines portfolio recommendation strategy
 * - Time horizon affects asset allocation recommendations
 * 
 * @author Wealth Management System
 * @version 1.0
 * @since Phase 4.2
 */
@Entity
@Table(name = "risk_profiles")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RiskProfile {
    
    /**
     * Unique identifier for risk profile.
     * Primary key, auto-generated by database.
     * Type: BIGINT AUTO_INCREMENT
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Reference to owning user.
     * One-to-one relationship (enforced by UNIQUE constraint at DB level).
     * Foreign key: user_id -> users.id
     * Type: BIGINT, NOT NULL, UNIQUE
     * Cascade: User deleted = RiskProfile deleted (managed by DB FK)
     */
    @OneToOne
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    
    /**
     * Calculated risk level from assessment.
     * Enum values: LOW, MEDIUM, HIGH
     * Stored as VARCHAR in database.
     * Type: ENUM('LOW','MEDIUM','HIGH'), NOT NULL
     * 
     * Determines portfolio recommendation:
     * - LOW: Conservative (70% bonds, 20% stocks, 10% cash)
     * - MEDIUM: Balanced (50% stocks, 40% bonds, 10% cash)
     * - HIGH: Aggressive (80% stocks, 15% bonds, 5% cash)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", nullable = false, length = 10)
    private RiskLevel riskLevel;
    
    /**
     * Investment time horizon in years.
     * Used to adjust portfolio recommendations.
     * Type: INT, NOT NULL
     * 
     * Common values:
     * - Short-term: 1-3 years
     * - Medium-term: 3-7 years
     * - Long-term: 7+ years
     * 
     * Example: 5 (for 5-year investment horizon)
     */
    @Column(name = "time_horizon_years", nullable = false)
    private Integer timeHorizonYears;
    
    /**
     * Timestamp when risk profile was created.
     * Auto-managed by JPA @PrePersist lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when risk profile was last updated.
     * Auto-managed by JPA @PreUpdate lifecycle callback.
     * Updates when user retakes risk assessment.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
