package com.wealthmanagementsystem.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * User entity representing system users.
 * 
 * Mapped to database table: users
 * 
 * Relationships (Phase 4.2 Batch 1):
 * - 1:1 with RiskProfile (one user = one risk profile)
 * 
 * Relationships (to be added in future batches):
 * - 1:N with Portfolio (Batch 2)
 * - 1:N with FinancialGoal (Batch 3)
 * 
 * @author Wealth Management System
 * @version 1.0
 * @since Phase 4.2
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {
    
    /**
     * Unique identifier for user.
     * Primary key, auto-generated by database.
     * Type: BIGINT AUTO_INCREMENT
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * User's email address.
     * Used for login and identification.
     * Must be unique across all users.
     * Type: VARCHAR(255), NOT NULL, UNIQUE
     * Example: user@example.com
     */
    @Column(nullable = false, unique = true, length = 255)
    private String email;
    
    /**
     * BCrypt hashed password.
     * Never store plain passwords.
     * BCrypt hash length: typically 60 characters.
     * Type: VARCHAR(255), NOT NULL
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;
    
    /**
     * User's full name for display.
     * Type: VARCHAR(255), NOT NULL
     * Example: John Doe
     */
    @Column(name = "full_name", nullable = false, length = 255)
    private String fullName;
    
    /**
     * Timestamp when user was created.
     * Auto-managed by JPA @PrePersist lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when user was last updated.
     * Auto-managed by JPA @PreUpdate lifecycle callback.
     * Type: TIMESTAMP, NOT NULL, DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    /**
     * One-to-one relationship with RiskProfile.
     * One user has exactly one risk profile.
     * Relationship is bidirectional, managed by RiskProfile side.
     */
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private RiskProfile riskProfile;
    
    // Relationships to be added in future batches:
    // - Portfolio collection (Batch 2)
    // - FinancialGoal collection (Batch 3)
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        createdAt = now;
        updatedAt = now;
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
